Hw02 unpack string
f0xx-otus/otus-home-work pull request #2
Opened 2020-03-15 22:56 UTC by f0xx-otus

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-03-18 07:40 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	fmt.Println(input)
Отладочную информацию убираем

2020-03-18 07:46 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/96662/6026/

Здравствуйте!

Спасибо за работу. У вас репозиторий сильно отстает от базового. Как обновиться - я писал недавно в Slack. Там же в дз2 есть уточнения по условию.

Давайте разберемся с текущими комментариями и продолжим после.
Благодарю :)

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input:    "",
Такой тест уже есть

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +	//t.Skip() // Remove if task with asterisk completed
Неактуальный код убираем

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input:    `\`,
Невалидная строка

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack_test.go
> +			input:    `\q`,
Невалидная строка

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	isNextSymbolEscaped := false
Предпочтительнее 

```
var isNextSymbolEscaped bool
```

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func multiplyLetters(runeSlice []rune, i int) string {
`strings.Repeat`?

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func TwoDigitCheck(i int, runeSlice []rune) (string, error) {
неэкспортируемая?

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +			return "", ErrInvalidString
экспортируемая функция возвращает ошибку, актуальную только в контексте Unpack - нехорошо

2020-03-18 07:46 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	fmt.Println(input)
Отладочную информацию убираем

2020-03-19 16:27 UTC, f0xx-otus commented on hw02_unpack_string/unpack_test.go
> +			input:    `\q`,
Я это, конечно, поправлю, но из начальных тестов и ТЗ это было совсем не очевидно)

2020-03-19 16:27 UTC, f0xx-otus commented on hw02_unpack_string/unpack_test.go
> +			input:    `\`,
И это тоже не совсем очевидно)

2020-03-20 06:19 UTC, Antonboom approved these changes
Достаточно многословное решение. Некоторые проверки и предварительные проходы можно сократить и осуществлять в основном цикле. По сути задача решается в один проход по строке с использованием пары флагов состояния.

Дополнительно обращаю внимание на:
* лишние копирования при конкатенации строк;
* то, что репозиторий все еще отстает от последней версии - можете потерять 2 новых ДЗ и поправки в условиях к остальным :);
* то, что можно пользоваться кнопкой "Resolve conversation", если считаете, что мое замечание более неактуально.

Спасибо за работу!
Принято
9 / 10

2020-03-20 06:19 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +func multiplyLetters(rune rune, i rune) string {
По сути теперь лишний метод :)

2020-03-20 06:19 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +	var output string
Пригодился бы `strings.Builder`

2020-03-21 15:57 UTC, f0xx-otus commented on hw02_unpack_string/unpack.go
> +func multiplyLetters(rune rune, i rune) string {
Мне самому вариант решения как-то не нравится, внутренне. Попробую на досуге переписать, если будет время)

2020-03-21 15:57 UTC, f0xx-otus commented on hw02_unpack_string/unpack.go
> +	var output string
Спасибо, почитаю

2020-03-21 15:58 UTC, merged