Hw04 lru cache
f0xx-otus/otus-home-work pull request #4
Opened 2020-04-09 00:31 UTC by f0xx-otus

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-04-09 06:13 UTC, Antonboom commented on hw04_lru_cache/cache_test.go
> +	wg.Add(1)
?

2020-04-13 09:16 UTC, farir1408 requested changes

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/cache.go
> -type cacheItem struct {
Подразумевалось, что это элемент кэша, который используется как значение в ListItem, и именно он помещался в очередь и в мапу с ключом. По сути можно рассматривать это как обёртку над ListItem.

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/list.go
> +	sync.Mutex
Зачем элементу мьютекс?

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/list.go
> +	sync.Mutex
В целом, можно было бы сделать список простой структурой, не потокобезопасной.

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/list.go
> +	First, Last *ListItem
Можно их сделать приватными, так как есть геттеры в виде Front и Back.

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/list.go
> +		l.Last = l.Last.Next
Лучше сначала сдвинуть l.Last, а потом присвоить указателю на предыдущее значение nil. Так более читабельно.

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/cache.go
> +	if _, ok := l.dict[key]; ok {
Можно сразу получить элемент из мапы, присвоить ему новое value и сделать MoveToFront.

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/cache.go
> +		if v.Value == l.queue.Back().Value {
Не очень понял зачем это условие?

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/cache.go
> +	if _, ok := l.dict[key]; ok {
Пропущенный параметр - это и есть ListItem.

2020-04-13 09:16 UTC, farir1408 commented on hw04_lru_cache/cache_test.go
> +	wg.Add(1)
Поддерживаю вопрос, запускается 2 горутины, и в обоих вызывается wg.Done(), однако в wg.Add(1), почему?

2020-04-13 21:26 UTC, f0xx-otus commented on hw04_lru_cache/cache_test.go
> +	wg.Add(1)
Извиняюсь - тестировал запуск горутин по отдельности, забыл вернуть значение

2020-04-13 21:32 UTC, f0xx-otus commented on hw04_lru_cache/list.go
> +	sync.Mutex
Неудаленный результат одной из попыток реализаций, удалил

2020-04-13 21:33 UTC, f0xx-otus commented on hw04_lru_cache/list.go
> +	sync.Mutex
Да, и правда. Оказалось, что это локи избыточны. Спасибо, убрал

2020-04-13 22:08 UTC, f0xx-otus commented on hw04_lru_cache/cache.go
> +		if v.Value == l.queue.Back().Value {
Так как элемент новый, и длина кэша уже максимальна, то нам нужно вытеснить самый редкоиспользуемый элемент (а это тот, который на последнем месте с нашем ListView)
Тут мы его и удаляем

2020-04-13 22:12 UTC, f0xx-otus commented on hw04_lru_cache/cache.go
> +	if _, ok := l.dict[key]; ok {
Ага, спасибо) Поправил

2020-04-13 22:17 UTC, f0xx-otus commented on hw04_lru_cache/cache.go
> +	if _, ok := l.dict[key]; ok {
Да, так читабельнее, спасибо

2020-04-13 22:24 UTC, f0xx-otus commented on hw04_lru_cache/cache.go
> -type cacheItem struct {
Я все еще не понимаю, в чем смысл этой обертки. И поэтому не совсем понимаю, куда и как ее можно вставить. Можете привести пример?

2020-04-14 12:38 UTC, farir1408 approved these changes

2020-04-14 12:38 UTC, farir1408 commented on hw04_lru_cache/cache.go
> -type cacheItem struct {
Например в `l.queue.PushFront(value)` подразумевалось, что будет `l.queue.PushFront(cacheItem{Key: key, Value: value})`.

2020-04-14 12:42 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.
Было бы круто увидеть тест, на выталкивание редко-используемых элементов. Суть его в том, что при получении элемента он автоматически перемещается в начало. То есть даже если элемент был добавлен последним, но затем его ни разу не получали, то этот элемент может быть удалён из кэша.

Принято 9/10.

2020-04-15 23:15 UTC, merged