Hw06 pipeline execution
f0xx-otus/otus-home-work pull request #7
Opened 2020-04-30 09:19 UTC by f0xx-otus

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-05-02 05:54 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/96662/6781/

Здравствуйте!

Распишите, пожалуйста, словами алгоритм вашего решения.
Кажется, что-то избыточно.

В комментариях я написал возможный вариант решения.
Обсудим?

2020-05-02 05:54 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +			tmpMap[inputItemIndex] = inputValue
Зачем этот map?

2020-05-02 05:54 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +	go func() {
Для чего вся эта логика? Я, признаться, с трудом понимаю

2020-05-02 05:54 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +	for v := range in {
Вам по сути необходимо реализовать зеркальную версию `Stage` (пример в тестах).
Основной цикл должен быть по стейджам - внутри логика связывания стейджов между собой и переназначение соотв. каналов

2020-05-02 05:54 UTC, Antonboom commented on hw06_pipeline_execution/pipeline.go
> +	wg := &sync.WaitGroup{}
wg здесь в принципе необязательна, главное в определенный момент закрыть выходной канал Out, чтобы читающая из него горутина могла остановить свою работу

2020-05-02 10:43 UTC, f0xx-otus commented on hw06_pipeline_execution/pipeline.go
> +	go func() {
Логика с мапой обеспечивает порядок. Я параллельно в горутинах читаю из входящего канала и, чтобы при записи в канал out обеспечить правильный порядок (значения должны быть отправлены в канал out в том же порядке, в каком были вычитаны из in) я их складываю в паму, а потом из нее вытаскиваю, используя index

2020-05-02 10:51 UTC, f0xx-otus commented on hw06_pipeline_execution/pipeline.go
> +	for v := range in {
Я решил распараллелить чуть по-другому. Логику описал чуть выше) Можно было параллелить и по стейджам, но там тоже нужна была бы логика по последовательной обработке, через мапу пне показалась проще. Возможно, я что-то упустил

2020-05-05 16:28 UTC, Antonboom approved these changes
Интересное решение!

Принято
10 / 10

2020-05-05 17:59 UTC, merged